// flow-typed signature: c7bc2ee524d09aafe1cbd3c4ce75172f
// flow-typed version: <<STUB>>/shell-env_v^2.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shell-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shell-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shell-env/index' {
  declare module.exports: $Exports<'shell-env'>;
}
declare module 'shell-env/index.js' {
  declare module.exports: $Exports<'shell-env'>;
}
