// flow-typed signature: 3d6e3a69fdd452a8007aa5c9ceea5afd
// flow-typed version: <<STUB>>/shell-path_v^2.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shell-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shell-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shell-path/index' {
  declare module.exports: $Exports<'shell-path'>;
}
declare module 'shell-path/index.js' {
  declare module.exports: $Exports<'shell-path'>;
}
