// flow-typed signature: c424c96d2ae3fb7dba12ad9f368e8cc5
// flow-typed version: <<STUB>>/spawn-sync_v^2.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spawn-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spawn-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'spawn-sync/index' {
  declare module.exports: $Exports<'spawn-sync'>;
}
declare module 'spawn-sync/index.js' {
  declare module.exports: $Exports<'spawn-sync'>;
}
